### ISSUE TITLE
`'ast' has no attribute 'Num'` error since upgrade to v3.14.0

### ISSUE THREAD

**Issue by jamietanna** [helm/chart-testing#780]
Since merging https://github.com/renovatebot/helm-charts/pull/3329 we're seeing [GitHub Actions failures](https://github.com/renovatebot/helm-charts/actions/runs/18355681820/job/52286941442?pr=3328):

```
> helm dependency build charts/renovate
Saving 1 charts
Downloading common from repo oci://registry-1.docker.io/bitnamicharts
Deleting outdated charts
Pulled: registry-1.docker.io/bitnamicharts/common:2.31.4
Digest: sha256:98cc992cb269f0b3f8f87c4bf933c1c0991b2d639f79e0bf62d1f35926efeb3f
Linting chart "renovate => (version: \"44.16.0\", path: \"charts/renovate\")"
> yamale --schema /opt/hostedtoolcache/ct/3.14.0/amd64/etc/chart_schema.yaml charts/renovate/Chart.yaml
Validating /home/runner/work/helm-charts/helm-charts/charts/renovate/Chart.yaml...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/bin/yamale", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/command_line.py", line 124, in main
    _router(args.path, args.schema, args.cpu_num, args.parser, not args.no_strict)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/command_line.py", line 104, in _router
    _validate_single(root, schema_name, parser, strict)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/command_line.py", line 69, in _validate_single
    _validate(s, yaml_path, parser, strict, True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/command_line.py", line 28, in _validate
    schema = yamale.make_schema(schema_path, parser)
...
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/syntax/parser.py", line 40, in parse
    _validate_expr(tree.body, validators)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/ct/3.14.0/amd64/venv/lib/python3.14/site-packages/yamale/syntax/parser.py", line 22, in _validate_expr
    ast.Constant, ast.Num, ast.Str, ast.Bytes, ast.NameConstant]
                  ^^^^^^^
AttributeError: module 'ast' has no attribute 'Num'
```

I'm wondering if the tests didn't run on the original PR bump, because nothing had changed in the chart?
